### PR TITLE
Reassign scripts

### PR DESCRIPTION
**Pull request by eva128**

### CODE REVIEW

**Comment by tropper26** [comment]
Best work I've seen so far from any collaborator!!! 🎉🎉🎉 👏👏👏

**Review by tropper26 — APPROVED** [review]

**Comment by andradademian** [comment]
Great work <3 @eva128 > @YannickLa (didn't do, in fact, anything)

**Comment by tropper26** [comment]
@YannickLa best man. Ever

**Comment by andradademian** [comment]
> @YannickLa best man to Ever exist

cap

**Review by andradademian — APPROVED** [review]
Girl power!! 🌸👯

**Pull request merged**
